### ISSUE TITLE
Typo in `4-external-computation/README.md`

### ISSUE THREAD

**Issue by jinxinglim** [runtimeverification/kontrol-workshop-ethcc-7#3]
I believe there is a typo in https://github.com/runtimeverification/kontrol-workshop-ethcc-7/tree/main/4-external-computation#1-generate-helper-contracts-with-kontrol.

`kontrol load-state-diff ...` -> `kontrol load-state` (at least this works for me in the latest version of Kontrol, i.e., v0.1.352.

**Comment by JuanCoRo** [comment]
Thank you! Just addressed this issue :pray:
